stages:
  - test
  - build
  - package
  - deploy

default:
  interruptible: true


variables:
  IMAGE_NAME: pradyumnajkumar/everythin-australia
  IMAGE_TAG: client

frontend_test:
  stage: test
  image: node:20-alpine
  script:
    - npm ci
    - npm test

frontend_build:
  stage: build
  image: node:20-alpine
  needs: ["frontend_test"]
  script:
    - npm ci
    - npm run lint || echo "Lint warnings ignored"
    - npm run build

build_image:
  stage: package
  image: docker:29.4.0
  services:
    - docker:29.4.0-dind
  variables:
    DOCKER_TLS_CERTDIR: "/certs"
  before_script:
    - echo "$PASSWORD" | docker login -u "$USER_NAME" --password-stdin
  script:
    - docker build -t $IMAGE_NAME:$IMAGE_TAG .
    - docker push $IMAGE_NAME:$IMAGE_TAG
  dependencies:
    - frontend_build  # Ensures build artifacts available

deploy:
  stage: deploy
  image: node:20-alpine
  needs: ["build_image", "frontend_build"]  # ✅ moved here
  environment:
    name: production
    url: https://the-aussie-outfit-frontend.vercel.app
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
      when: manual
  script:
    - npm i -g vercel
    - vercel --prod --token $VERCEL_TOKEN --yes
